// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biographyy: dynamic(() => import("./Biographyy")),
  content_index: dynamic(() => import("./ContentIndex")),
  hero: dynamic(() => import("./Hero")),
  tech_listt: dynamic(() => import("./TechListt")),
  text_block: dynamic(() => import("./TextBlock")),
};
